Finish portfolio project
eamador1/personal-portfolio pull request #4
Opened 2023-03-31 23:21 UTC by eamador1

In this project, I made the following changes since the last review:

- [ ] Add content to the projects section and about me section
- [ ] Add header tags
- [ ] Change to make it look like template

2023-04-01 04:29 UTC, Kamba56 requested changes
Hi @eamador1, 

Good job so far!!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Great using grid and flexbox to layout contents of your page.!👏👏👏
- [x] Good job adding the works and about sections

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 04:29 UTC, Kamba56 commented on index.html
> +    </section>
- [ ] Great job adding the contact section. But the section is coming in the upcoming milestone. I suggest you stash it somewhere and implement it when the time comes. You are supposed to build your portfolio one step at a time.

2023-04-01 04:29 UTC, Kamba56 commented on index.html
> +        </div>
- [ ] Please as demanded by the project requirements, kindly use a nested unordered list to list out your technology categories and category technologies. The technology categories ("Languages", "Frameworks" and "Skills") are in a ul, each of them in a li, and the technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list ul and each of them a li.
Kindly use the example below as an example.
```html
<ul>
  <li>Languages
    <ul>
      <li>HTML</li>
      <li></li>
      <li></li>
    </ul>
  </li>
  <li>Frameworks
    <ul>
      <li>React</li>
      <li></li>
      <li></li>
    </ul>
  </li>
  <li>Skills
    <ul>
      <li>Database</li>
      <li></li>
      <li></li>
    </ul>
  </li>
</ul>
```

- [ ] KIndly add the margins between the technology categories. Also aligned them on the left and add the bullet points to match the template.
### Your design
![image](https://user-images.githubusercontent.com/94551484/229265406-0ae0f719-0882-4729-855b-bcabc2262e92.png)
### Figma
![image](https://user-images.githubusercontent.com/94551484/229265451-6fcd65d4-ac26-48d6-9f72-7c824b494e52.png)

2023-04-01 04:29 UTC, Kamba56 commented on style.css
>  @media all and (max-width: 767px) {
- [ ] You are expected to build this portfolio using the mobile-first approach. This means that all mobile styles should be outside any media query and written first before a media query will be used to implement the desktop version. The desktop version is coming up in a future milestone. Kindly remove the media query and write your mobile CSS directly in your CSS file.

2023-04-01 04:29 UTC, Kamba56 commented on index.html
> +            <button class="button button2">Get my CV</button>
- [ ] The about section is aligned on the left in the figma template. Kindly align all the elements here on the left to match the template.
### Your design
![image](https://user-images.githubusercontent.com/94551484/229265190-cabfe3a5-c8bc-44be-92d2-573ca2932c15.png)
### Figma
![image](https://user-images.githubusercontent.com/94551484/229265203-09e28e37-d7d7-490e-aaf3-9c8bf5e2c4e0.png)

2023-04-01 04:29 UTC, Kamba56 commented on style.css
> +  }
- [ ] The font-weight of your headings looks thicker than the template. Kindly reduce it to match the design template.
### Your headings
![image](https://user-images.githubusercontent.com/94551484/229265256-ab84dd0f-7227-400f-b9c5-65c83ad1bee8.png)
![image](https://user-images.githubusercontent.com/94551484/229265264-d227e38d-ad30-40e8-a992-d5f64d7781fb.png)
### Figma
![image](https://user-images.githubusercontent.com/94551484/229265281-2790e750-5ff5-4f27-8db7-815b64002aa8.png)
![image](https://user-images.githubusercontent.com/94551484/229265291-339b46c2-f171-4442-acd3-83f42f973005.png)

2023-04-01 21:07 UTC, eamador1 commented
After last review, the following changes were made:

- [ ] Change  font in headings
- [ ] Use correct indentation in the codes
- [ ] Make cards take 100% of the page
- [ ] Use hover in buttons
- [ ] Delete contact section (To be added later)
- [ ] Change appearance of design to be more like template

2023-04-01 22:17 UTC, adel-gu requested changes
# Status: REQUIRED CHANGES ♻️ 

**Hi @eamador1 👋🏼** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![](https://media1.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif?cid=ecf05e479q7yo5m5i0bj5otulguwaad4ujt7nfnslla9ylpz&rid=giphy.gif&ct=g)


 ## Highlights
- The Design following the Mobile-first approach ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 22:17 UTC, adel-gu commented on index.html
> +            you see and have a project you need coded, don't hesitate
- [ ] As requested by the previous reviewer please consider fixing the About section content alignment, currently the `Get My CV` button has a left spacing that results in the layout mess.

## Your Design
![image](https://user-images.githubusercontent.com/68030297/229315864-65dcca66-82a2-4091-a3cf-796a9478d977.png)

## Figma Design
![image](https://user-images.githubusercontent.com/68030297/229315876-aeeadaa3-4c13-4d46-afd9-a83a8826e61b.png)

## Suggessions

- This can be solved by targeting the class `.button2` and updating the `width` property from `360px` to `100%` to take up the whole space as shown in the Figma design.

2023-04-01 22:17 UTC, adel-gu commented on style.css
> +}
- [ ] As requested by the previous reviewer the current weight of all headers in your website looks thicker than those on the Figma design system, please stick to the design as much as possible and check for the correct font weight from Figma by following these steps:

- From Figma Select the text.
- Check the style from the right panel, look for `font-weight` 👍🏼 

![image](https://user-images.githubusercontent.com/68030297/229316101-f392fed0-503a-4034-bd51-7e6541f83a19.png)

### Your Design
![image](https://user-images.githubusercontent.com/68030297/229316110-2a31c265-0c6b-47af-bf38-4d952ce9212b.png)
![image](https://user-images.githubusercontent.com/68030297/229316115-4a16386f-098d-4a14-ba99-e0570519ddfe.png)

### Figma Design
![image](https://user-images.githubusercontent.com/68030297/229316124-ea7882f4-9d03-4058-a133-763c189a9088.png)
![image](https://user-images.githubusercontent.com/68030297/229316128-9a0206a6-295c-4559-8d3a-5c4742832317.png)

2023-04-01 22:17 UTC, adel-gu commented on style.css
> +}
- [ ] As requested by the previous reviewer about adding hover and pressed state to all your buttons according to how they appear on your design, please consider fixing this issue by adding the right styling for each interaction following the Figma Design 👍🏼 

## Your Design
![image](https://user-images.githubusercontent.com/68030297/229316311-51dbea49-389b-48cc-a1a5-5910fdfde70e.png)

## Figma Design
![Screenshot from 2023-04-01 23-13-41](https://user-images.githubusercontent.com/68030297/229316333-1deeffd0-179b-4048-bb09-c1fcc9ec2a99.png)

## Suggesstions

Please follow this example:

```css
.your-button-class:hover,
.your-button-class:focus, {
    background-color: none;
    border: 1px solid #1A2236;
    color: #1A2236;
}

.your-button-class:focus {
    border-width: 2px;
}
```

2023-04-02 01:57 UTC, eamador1 commented
Since the last review, the following changes were made:

- [ ] Change hover and pressed effect to buttons
- [ ] Increase collaboration button size
- [ ] Change font weight (By using lighter and bolder weight option)
- [ ] Add see this project button

2023-04-02 02:23 UTC, Owusu-Desmond requested changes
Hi @eamador1 , :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-02 02:23 UTC, Owusu-Desmond commented on index.html
> +      </div>
- [ ] You have made a lot of changes requested by the previous reviewers, :-1:  However, while making the changes your `see project` does not match the Figma design as you can see below :point_down:
    - You are missing the arrow and the button text should take one line. 

### Your Design
![image](https://user-images.githubusercontent.com/92303891/229327566-46d0a570-7d96-4f9f-9268-c4dd41d746db.png)

### Figma design
![image](https://user-images.githubusercontent.com/92303891/229327592-91af87a1-0f26-4938-9852-18fc92e6b9db.png)

2023-04-02 02:56 UTC, eamador1 commented on index.html
> +      </div>
hello @Owusu-Desmond, thank you for taking the time to review the project. I was looking at my project and I do not have that issue you want me to fix.

<img width="437" alt="Screen Shot 2023-04-01 at 20 51 37" src="https://user-images.githubusercontent.com/124623610/229328574-08ceffe4-5276-4e7e-8eeb-88c87afe6944.png">

Let me know how I can solve this issue. Thank you, again.

2023-04-02 03:21 UTC, eamador1 commented on index.html
> +      </div>
Hello again, @Owusu-Desmond. Here I send you a  full screen-shot. So you can fully see, what I see here. Let me know what we can do.
<img width="1454" alt="Screen Shot 2023-04-01 at 21 19 52" src="https://user-images.githubusercontent.com/124623610/229329420-1fccb3c3-9c44-4020-babc-bd338603191d.png">

2023-04-03 20:43 UTC, merged