Create contact form
eamador1/personal-portfolio pull request #5
Opened 2023-04-05 16:21 UTC by eamador1

Since the last review, we worked on the following changes:

- [ ] Add a contact form
- [ ] Test linters

2023-04-05 17:02 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @eamador1, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 17:02 UTC, bobb-Rob commented on index.html
> +      <form action="forms/" method="post">
- [ ] Based on the project requirement, the submission of this form should be handled by [formspree](https://formspree.io/html). This means that you will create an account with Formspree, get a `form_id` then, copy your unique form url for use in the form element as shown below 👇🏾 

```html
  <form action="https://formspree.io/f/form_id" method="post"> 
```

In the action property above, replace the form_id text there with your actual form_id value obtained from your Formspree account. 

```html
  <form action="https://formspree.io/f/23ead6" method="post"> <!--  the form_id was replaced with my formspree generated Id which is 23ead6 -->
```

2023-04-05 17:51 UTC, eamador1 commented
Since last review, the following changes were implemented:

- [ ] Give text-boxes a 4px border-radius
- [ ] Change email type to email
- [ ] Change border attribute to none
- [ ] Implement form submission handled by spree

2023-04-05 18:13 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @eamador1 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 19:40 UTC, merged

2023-04-06 14:26 UTC, eamador1 commented on style.css
>  }
Great job with the coding. Good indentation, spaces between attributes are just one line. Good job overall.

2023-04-06 14:29 UTC, eamador1 reviewed
You did a great job in your coding. Good indentation and spacing.

2023-04-07 15:11 UTC, sylvester-wamaya commented on style.css
> +  color: #1a2236;
I kindly suggest you add `padding-top` on the email input so that your design looks like Figma's template.

2023-04-07 15:12 UTC, sylvester-wamaya reviewed
Good job on your progress!
Please check comments to make more improvements on your project.